CREATE TABLE Admin(
	AdminId INT IDENTITY PRIMARY KEY,
	AdminName VARCHAR(50) NOT NULL,
	AdminEmail VARCHAR(100) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	CnfPassword VARCHAR(32) NOT NULL,
	AdminPhone VARCHAR(10) NOT NULL,
	CityId INT FOREIGN KEY REFERENCES City(CityId),
	AccessId  VARCHAR(10) FOREIGN KEY REFERENCES [Access Control](AccessId),
	LastLogin DATETIME2 DEFAULT GETDATE(),
	FailedLoginAttempts INT DEFAULT 0,
	CreatedBy VARCHAR(50),
	CreatedAt DATETIME2 DEFAULT GETDATE(),
	ModifyBy VARCHAR(50),
	ModifyAt DATETIME2 DEFAULT GETDATE(),
	isActive BIT DEFAULT 1
)

ALTER TABLE Admin
ALTER COLUMN ModifyBy UNIQUEIDENTIFIER;



ALTER TABLE Admin
ADD CONSTRAINT FK_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES [All User Table](UID);


ALTER TABLE Admin
ADD CONSTRAINT FK_ModifyBy FOREIGN KEY (ModifyBy) REFERENCES [All User Table](UID);


DROP TABLE Admin;

SELECT * FROM Admin;

