CREATE TABLE Admin(
	AdminId INT IDENTITY PRIMARY KEY,
	AdminName VARCHAR(50) NOT NULL,
	AdminEmail VARCHAR(100) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	CnfPassword VARCHAR(32) NOT NULL,
	AdminPhone VARCHAR(10) NOT NULL,
	--AccessId  INT FOREIGN KEY REFERENCES [Access Control](AccessId),
	--CityId INT FOREIGN KEY REFERENCES City(CityId),
	LastLogin DATETIME2 DEFAULT GETDATE(),
	FailedLoginAttempts INT DEFAULT 0,
	CreatedBy VARCHAR(36) DEFAULT 'D61BEC2C-FB2C-4B55-A1A4-A2B3DC4B3D02',
	CreatedDate DATETIME2 DEFAULT GETDATE(),
	ModifyBy VARCHAR(36) DEFAULT 'D61BEC2C-FB2C-4B55-A1A4-A2B3DC4B3D02',
	ModifyDate DATETIME2 DEFAULT GETDATE(),
	isActive BIT DEFAULT(1)
)


SELECT * FROM Admin;


DROP TABLE Admin;

