CREATE TABLE Country(
	CountryId INT IDENTITY  PRIMARY KEY,
	CountryName VARCHAR(50) NOT NULL,
	Abbreviation VARCHAR(20) NOT NULL,
	Currency NVARCHAR(30) NOT NULL,
	DialingCode INT NOT NULL,
	TimeZone VARCHAR(50),
	CountryCapital VARCHAR(50) NOT NULL,
	Flag NVARCHAR(MAX) NOT NULL,
    CreatedBy NVARCHAR(255),  
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    ModifiedBy NVARCHAR(255),
    ModifiedAt DATETIME2 DEFAULT GETDATE(),
    isActive BIT DEFAULT 0
)

SELECT * FROM Country;

DROP TABLE Country;