CREATE TABLE Geofence(
	GeofenceId INT IDENTITY PRIMARY KEY,
	AreaName VARCHAR(50) NOT NULL,
	AreaType NVARCHAR(MAX) NOT NULL,
	Coordinates NVARCHAR(MAX),
	StartDate DATETIME2 DEFAULT GETDATE(),
	EndDate DATETIME2 DEFAULT GETDATE(),
	Reason NVARCHAR(MAX),
	--CityId INT FOREIGN KEY REFERENCES City(CityId),
	CreatedBy NVARCHAR(255),  
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    ModifiedBy NVARCHAR(255),
    ModifiedAt DATETIME2 DEFAULT GETDATE(),
    isActive BIT DEFAULT 0
)

SELECT * FROM Geofence;

DROP TABLE Geofence;