CREATE TABLE Promocode (
	PromoCodeId INT IDENTITY PRIMARY KEY,
	ValidFrom DATETIME2 NOT NULL,
	ExpiryDate DATETIME2 NOT NULL,
	[Discount %] INT NOT NULL,
	ReferredBy VARCHAR(50)
)

SELECT * FROM Promocode