CREATE TABLE Setting(
	SettingId INT IDENTITY PRIMARY KEY,
	RIDETIMEOUT INT NOT NULL DEFAULT 10,
	STOPS INT NOT NULL DEFAULT 0,
	EMAIL_USER  NVARCHAR(MAX),
	EMAIL_PASSWORD NVARCHAR(MAX),
	AccountSid NVARCHAR(MAX),
	AuthToken NVARCHAR(MAX),
	Twilio_PhoneNumber VARCHAR(10),
	STRIPE_Secret_key NVARCHAR(MAX),
	STRIPE_Publishable_key NVARCHAR(MAX),
)